coverage:
  status:
    project:
      default:
        target: 65%
        threshold: 2%
    patch:
      default:
        target: 60%

ignore:
  - "examples/**"
  - "**/tests.rs"
  - "**/property_tests.rs"
  - "fuzz/**"
  - "tests/fixtures/**"
